    1: Result := @XTL_EmuRtlAllocateHeap;
    2: Result := @XTL_EmuRtlCreateHeap;
    3: Result := @XTL_EmuRtlFreeHeap;
    4: Result := @XTL_EmuRtlReAllocateHeap;
    5: Result := @XTL_EmuRtlSizeHeap;
    6: Result := @XTL_EmuXapiApplyKernelPatches;
    7: Result := @XTL_EmuXapiInitProcess;
    8: Result := @XTL_EmuXapiThreadStartup;
    9: Result := @XTL_EmuXRegisterThreadNotifyRoutine;

