  XTL_EmuRtlAllocateHeap: string = '_RtlAllocateHeap@12';
  XTL_EmuRtlCreateHeap: string = '_RtlCreateHeap@24';
  XTL_EmuRtlFreeHeap: string = '_RtlFreeHeap@12';
  XTL_EmuRtlReAllocateHeap: string = '_RtlReAllocateHeap@16';
  XTL_EmuRtlSizeHeap: string = '_RtlSizeHeap@12';
  XTL_EmuXapiApplyKernelPatches: string = '_XapiApplyKernelPatches@0';
  XTL_EmuXapiInitProcess: string = '_XapiInitProcess@0';
  XTL_EmuXapiThreadStartup: string = '_XapiThreadStartup@8';
  XTL_EmuXRegisterThreadNotifyRoutine: string = '_XRegisterThreadNotifyRoutine@8';

